spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:postgresql://localhost:5432/omer
    username: postgres
    password: 123
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 300000 # 5 minutes
      connection-timeout: 30000 # 30 seconds
      max-lifetime: 1800000 # 30 minutes
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
    defer-datasource-initialization: true
